@include('components.script-berkas-kepegawaian.pendidikan-script', [
    'tableIjazahId' => 'tb-ijazah',
    'tableTranskripId' => 'tb-transkrip',
    'ijazahRoute' => 'berkas.getIjazah',
    'ijazahStoreRoute' => 'berkas.ijazah.store',
    'ijazahEditRoute' => 'berkas.ijazah.edit',
    'ijazahUpdateRoute' => 'berkas.ijazah.update',
    'ijazahDestroyRoute' => 'berkas.ijazah.destroy',
    'transkripRoute' => 'berkas.getTranskrip',
    'transkripStoreRoute' => 'berkas.transkrip.store',
    'transkripEditRoute' => 'berkas.transkrip.edit',
    'transkripUpdateRoute' => 'berkas.transkrip.update',
    'transkripDestroyRoute' => 'berkas.transkrip.destroy',
    'verifIjazahStoreRoute' => 'verif.ijazah.store',
    'verifIjazahDestroyRoute' => 'verif.ijazah.destroy',
    'routeIjazahPDF' => '/karyawan/ijazah/view/',
    'routeVerifIjazahPDF' => '/karyawan/ijazah/verif/view/',
    'routeTranskripPDF' => '/karyawan/transkrip/view/',
])
