@include('components.script-berkas-kepegawaian.sip-script', [
    'tableId' => 'tbSIP',
    'strRoute' => 'file.str.get',
    'sipRoute' => 'berkas.getSIP',
    'sipStoreRoute' => 'berkas.sip.store',
    'sipEditRoute' => 'berkas.sip.edit',
    'sipUpdateRoute' => 'berkas.sip.update',
    'sipDestroyRoute' => 'berkas.sip.destroy',
    'strSelectedRoute' => 'selected.str.get',
    'sipExpRoute' => 'berkas.sip.exp',
    'sipDesexpRoute' => 'berkas.sip.desexp',
    'sipStatusRoute' => 'berkas.sip.status',
    'enablePaging' => false,
    'enableSearch' => false,
    'enableInfo' => false,
    'showActions' => true,
    'showStatusActions' => true,
    'modalParent' => '#modaladdSIP',
    'editModalParent' => '#modaleditSIP',
    'idpegawai' => 'idpegawai',
    'routePDF' => '/karyawan/sip/view/',
    'aksesPage' => 'admin',
    'permissionsSIP' => [],
])
