<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PenilaianMCU extends Model
{
    use HasFactory;
    protected $connection = 'mysql2';
    protected $table = "penilaian_mcu";
    protected $fillable = [
        'no_rawat',
        'tanggal',
        'kd_dokter',
        'informasi',
        'rps',
        'rpk',
        'rpd',
        'alergi',
        'keadaan',
        'kesadaran',
        'td',
        'nadi',
        'rr',
        'tb',
        'bb',
        'suhu',
       ' submandibula',
        'axilla',
        'supraklavikula',
        'leher',
        'inguinal',
        'oedema',
        'sinus_frontalis',
        'sinus_maxilaris',
        'palpebra',
        'sklera',
        'cornea',
        'buta_warna',
        'konjungtiva',
        'lensa',
        'pupil',
        'lubang_telinga',
        'daun_telinga',
        'selaput_pendengaran',
        'proc_mastoideus',
        'septum_nasi',
        'lubang_hidung',
        'bibir',
        'caries',
        'lidah',
        'faring',
        'tonsil',
        'kelenjar_limfe',
        'kelenjar_gondok',
        'gerakan_dada',
        'vocal_femitus',
        'perkusi_dada',
        'bunyi_napas',
        'bunyi_tambahan',
        'ictus_cordis',
        'bunyi_jantung',
        'batas',
        'inspeksi',
        'palpasi',
        'hepar',
        'perkusi_abdomen',
        'auskultasi',
        'limpa',
        'costovertebral',
        'kondisi_kulit',
        'ekstrimitas_atas',
        'ekstrimitas_atas_ket',
        'ekstrimitas_bawah',
        'ekstrimitas_bawah_ket',
        'laborat',
        'radiologi',
        'ekg',
        'spirometri',
        'audiometri',
        'treadmill',
        'lainlain',
        'merokok',
        'alkohol',
        'kesimpulan',
        'anjuran',

    ];
}
